### Test Audit Log Retrieval
# POST http://localhost:4004/odata/v4/audit-log/retrieveAuditLogs
# Content-Type: application/json

POST https://crossfunctional-dev-org-rakpoc-auditlog-srv.cfapps.eu10.hana.ondemand.com/odata/v4/audit-log/retrieveAuditLogs
Content-Type: application/json
Authorization: Bearer <token>